version: 2.1

jobs:
  test-build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      # run build
      - run:
          name: install dependencies
          command: |
            sudo npm install 
            sudo npm install -g htmlhint

      # run lint
      - run:
          name: HTML Linting
          command: sudo npm run lint:html

  upload-docker:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build docker container
          command: |
            sudo docker build -t remambian/capstoneimage:latest . 

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push to Docker Hub
          command: docker push remambian/capstoneimage:latest
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yum install -y tar gzip
      - run:
          name: Ensure EKS network exists
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/network.yml \
              --tags project=${ENVIRONMENT_NAME}-project \
              --stack-name "${ENVIRONMENT_NAME}-eks-network" \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides file://cloudformation/network-parameters.json



workflows:
  default:
    jobs:
      - test-build
      - upload-docker:
          requires:
            - test-build
      - deploy-infrastructure